"""Initial migration.

Revision ID: 492e35725827
Revises: d5652450126e
Create Date: 2024-02-27 11:21:07.495529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492e35725827'
down_revision = 'd5652450126e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('subject2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('subject3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('High1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('High2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('High3', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('High3')
        batch_op.drop_column('High2')
        batch_op.drop_column('High1')
        batch_op.drop_column('subject3')
        batch_op.drop_column('subject2')
        batch_op.drop_column('subject1')

    # ### end Alembic commands ###
