"""Added hours column

Revision ID: d5652450126e
Revises: 
Create Date: 2024-02-27 11:09:29.259384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5652450126e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    op.drop_table('tutor')
    op.drop_table('note')
    op.drop_table('student')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hours')

    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hours', sa.INTEGER(), nullable=False),
    sa.Column('list_classes', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('goal_id', sa.INTEGER(), nullable=False),
    sa.Column('effort', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hours', sa.INTEGER(), nullable=False),
    sa.Column('list_classes', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('completion_date', sa.DATE(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
